### ISSUE TITLE
import of module jabber failed

### ISSUE THREAD

**Issue by caiyingchun** [degiacom/JabberDock#1]
When I run dock.py, I meet this error:
```Traceback (most recent call last):
  File "/home/applic/POW_v2/POW.py", line 153, in <module>
    fitness=comm.bcast(fitness,root=0)
  File "mpi4py/MPI/Comm.pyx", line 1257, in mpi4py.MPI.Comm.bcast
  File "mpi4py/MPI/msgpickle.pxi", line 628, in mpi4py.MPI.PyMPI_bcast
  File "mpi4py/MPI/msgpickle.pxi", line 104, in mpi4py.MPI.Pickle.dump
  File "mpi4py/MPI/msgpickle.pxi", line 91, in mpi4py.MPI.Pickle.cdumps
cPickle.PicklingError: Can't pickle <class 'jabber.Jabber'>: import of module jabber failed
```
How to slove it?
Thanks

**Comment by dclw29** [comment]
Hi,
Thanks for the notification, we actually just discovered this bug only yesterday. Essentially it was down to a pickling error from mpi4py when it couldn't send the jabber.Jabber() class objects (our protein maps) to the slave processors.

I've updated the POW.py module now so it should be working (so you will need to git pull, or just copy the python file directly) - all slave processors will do their own pre-processing. This is not ideal, but it is a workaround for now. It might need a little more memory now however, so if you encounter a memory issue please run across a smaller number of processors, or try and use a HPC with more onboard RAM. The memory requirements are an ongoing issue we're trying to resolve.

Also note you will now need to install dill:
`pip install dill`
And we recommend installing mpi4py version 3.0.0:
`pip install mpi4py==3.0.0`
Cheers,
Lucas

**Comment by caiyingchun** [comment]
Thanks very much! It works.

________________________________
发件人: dclw29 <notifications@github.com>
发送时间: 2020年5月20日 10:05
收件人: degiacom/JabberDock <JabberDock@noreply.github.com>
抄送: Yingchun Cai <cai_yingchun@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [degiacom/JabberDock] import of module jabber failed (#1)


Hi,
Thanks for the notification, we actually just discovered this bug only yesterday. Essentially it was down to a pickling error from mpi4py when it couldn't send the jabber.Jabber() class objects (our protein maps) to the slave processors.

I've updated the POW.py module now so it should be working - all slave processors will do their own pre-processing. This is not ideal, but it is a workaround for now. It might need a little more memory now however, so if you encounter a memory issue please run across a smaller number of processors, or try and use a HPC with more onboard RAM. The memory requirements are an ongoing issue we're trying to resolve.

Also note you will now need to install dill:
pip install dill
And we recommend installing mpi4py version 3.0.0:
pip install mpi4py==3.0.0
Cheers,
Lucas

―
