### ISSUE TITLE
Error importing 'biobox' module

### ISSUE THREAD

**Issue by aaayushg** [degiacom/JabberDock#4]
Installed biobox using "python setup.py install" and folder is in $PYTHONPATH. But when I try to import, I get module not found error (tried with python2/3). Thanks for your help in advance.

**Comment by dclw29** [comment]
Hi! Can you please post your $PYTHONPATH as well as the path to the folder biobox is located in.

**Comment by aaayushg** [comment]
Biobox is located in /home/aayush/Documents/JabberDock/biobox
and PYTHONPATH is set to /home/aayush/Documents/JabberDock/biobox

**Comment by aaayushg** [comment]
It works now. There were some issues with environment. Thanks
